---
abstract: 'Authenticate against remote HTTP server'
author:
  - 'Nigel Metheringham <nigelm@cpan.org>'
build_requires:
  Carp: 0
  Catalyst::Authentication::Store::Minimal: 0
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  HTTP::Request::AsCGI: 0
  HTTP::Server::Simple::CGI: 0
  MIME::Base64: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-RemoteHTTP
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Exception: 0
  Catalyst::Runtime: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  namespace::autoclean: 0
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/nigelm/Catalyst-Authentication-Credential-RemoteHTTP/
version: 0.03
