---
abstract: 'Authenticate against remote HTTP server'
author:
  - 'Nigel Metheringham <nigelm@cpan.org>'
build_requires:
  Catalyst::Authentication::Store::Minimal: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  HTTP::Server::Simple: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-RemoteHTTP
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 0
  Class::Accessor::Fast: 0
  Class::Inspector: 0
  MRO::Compat: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/nigelm/Catalyst-Authentication-Credential-RemoteHTTP/
version: 0.02
